### ISSUE TITLE
Error 13 on call to libftw.so.0.8.0

### ISSUE THREAD

**Issue by emetzlervsi** [featherweight/featherweight#104]
I have built `kernel` on a 9068 and put it in `/usr/lib`, but when I run `FTW-KernelFilepath.vi` I get this error:

```
Error 13 occurred at Call Library Function Node in FTW-KernelFilepath.vi

Possible reason(s):

LabVIEW:  Failed to load dynamic library because of missing external symbols or dependencies, or because of an invalid file format.
```

This is an improvement over earlier efforts when I got error 7 (can't find file), so I believe that LabVIEW is able to find the lib at least.

**Comment by JackDunaway** [comment]
@emetzlervsi, glad to see you've been making progress here; I'm traveling
and slow to respond.

It's been a while since I've compiled on this target, but it looks like
you're headed in the right direction.

Taking a shot in the dark, but is it 'lib64' vs 'lib' that would work?

Kind regards,

- JRD
Sent via mobile

On Dec 8, 2016, at 1:48 PM, Eric Metzler <notifications@github.com> wrote:

I have built kernel on a 9068 and put it in /usr/lib, but when I run
FTW-KernelFilepath.vi I get this error:

Error 13 occurred at Call Library Function Node in FTW-KernelFilepath.vi

Possible reason(s):

LabVIEW:  Failed to load dynamic library because of missing external
symbols or dependencies, or because of an invalid file format.

This is an improvement over earlier efforts when I got error 7 (can't find
file), so I believe that LabVIEW is able to find the lib at least.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/featherweight/featherweight/issues/104>, or mute the
thread

**Comment by emetzlervsi** [comment]
Thanks @JackDunaway! I'm not sure which "lib" your're referring to, but I had not named the library as lib64 at all and I believe that `FTW-KernelFilepath.vi` is looking for `libftw.so`, so I believe the search name and target file name match. I snooped the dependencies and did not see anything with "64" in the name.

**Comment by JackDunaway** [comment]
The directory usr lib64; not filename. Again, a shot in the dark here. That
said, error 13 opposed to error 7 indicates it's at least able to locate,
so this is unlikely the issue. I can take a deeper look next week; keep us
posted in the meanwhile.

Kind regards,

- JRD
Sent via mobile

On Dec 8, 2016, at 2:45 PM, Eric Metzler <notifications@github.com> wrote:

Thanks @JackDunaway <https://github.com/JackDunaway>! I'm not sure which
"lib" your're referring to, but I had not named the library as lib64 at all
and I believe that FTW-KernelFilepath.vi is looking for libftw.so, so I
believe the search name and target file name match. I snooped the
dependencies and did not see anything with "64" in the name.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/featherweight/featherweight/issues/104#issuecomment-265878545>,
or mute the thread

**Comment by emetzlervsi** [comment]
I don't see a lib64 dir in `/usr`.

![image](https://cloud.githubusercontent.com/assets/6587287/21053482/9f049af6-bdf7-11e6-8e82-e13bf94aa583.png)

It seems that all the dependencies are in `/usr/lib`. I agree that 13 is better than 7. I had some location issues at first, but I think I've at least moved beyond that.

**Comment by emetzlervsi** [comment]
It took me a while, but I eventually figured out the incantations for making this work. I put the lib in `/usr/lib`, but it also needed to have a link to `liblvrt.so.15.0` in `/usr/lib`. Seems to be working now.

**Comment by emetzlervsi** [comment]
Also, not sure if this is documented anywhere, but I have added a README.md file to lib to explain this.
