### ISSUE TITLE
Support Element Path in JSON Getters

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#105]
To avoid extra serializations (or deserializations, depending on implementation choice), it would be nice to support an element path vs simply a key input on JSON getters.

The absence of any "path delimiters" would imply treating the input string as a simple key.

Important here would be support for "escaping" (ex. slashing) the path delimiter for cases where that key itself contains the path delimiter (as in, it's intended as part of the key / name, not part of a path specification).

**Comment by JackDunaway** [comment]
Agree; working on it.

Unfortunately, there's no canonical syntax for JSON paths, so I'm planning to use that adopted by SQLite (see: [`jsonLookupStep()`](https://www.sqlite.org/src/artifact/552a7d730863419e))

Briefly, the `.` operator is used to select elements within objects, and the `[]` operator to select array elements (no surprises here). Any level surrounded by double quotes `"` will be treated literally, which allows for both operators to be part of an object's key name (this literal/escaping method is the only departure from your suggestion of slashing).

**Comment by JackDunaway** [comment]
Here's a screenshot of a preliminary test that's passing -- any feedback on coverage?

![screen shot 2017-02-02 at 3 56 22 pm](https://cloud.githubusercontent.com/assets/1944203/22570377/a3391982-e960-11e6-94a2-56616606cd6d.png)

**Comment by jassems** [comment]
First quick thoughts:

1. add a key with a period and test both success w/ quotes and failure w/o
quotes (assuming / enforcing that it doesn't incidentally resolve to a
valid path).

2. Test failure of use of [ and ] w/o quotes assuming those are both
treated as special characters.  If only the use of [ ] is special then test
that.  If only the use of [m] where m in an integer, then test that.

3. Test that array indexing fails if m is not an integer when indexing an
array such as CompositeArrray[m]

Question: if you want to return an object can you specify a JSON type and
have it return a new JSON object instance?

Looking good, thanks!!!

**Comment by jassems** [comment]
PS - I like the quoted special character handling better than slashing -
cleaner - however can one slash a quote to include it as part of a key?

**Comment by JackDunaway** [comment]
1. Good idea; added `Key.With.Periods` (see below)
2. Added more test coverage here also. Additionally, I came across a good reason to go ahead and implement the ability to iterate through object elements based on their *ordered index*, not just *key*. Added tests for this, too. (especially: note the difference between `[0]` and `"[0]"`, where the first path selects the first element in the object, and the second path selects the key that exists whose name is `[0]`.
3. I'll add coverage for invalid paths as a new test -- there's plenty more negative test coverage that needs to happen.

> "if you want to return an object can you specify a JSON type and have it return a new JSON object instance?"

No, because this pretty dangerous, since you have to have detailed knowledge about how the underlying Jansson borrow system works. A long time ago, FTW provided this capability, but even with pretty deep understanding, I'd continually create either 1) memory leaks or worse 2) access-after-free bugs, since it's hard to know exactly when and where to `FTW-JSON-Destroy`.

That said, with these new path abilities, the desire to do this should be greatly diminished!

> "however can one slash a quote to include it as part of a key?"

Right now, no, but that would probably not be too hard to add. I'll update this case once the code is pushed referencing the lines where this would need to be in `ftw_json.c`.

![screen shot 2017-02-03 at 4 33 00 pm](https://cloud.githubusercontent.com/assets/1944203/22611426/0e3be848-ea30-11e6-9ac2-b017c30ed88d.png)

**Comment by jassems** [comment]
Awesome all around!

On theoretical quote character escaping - not terribly concerned about
needing a " in keys, but could imagine cases where digesting another asset
to build up some JSON could could bump into this.  Thanks for the code line
ref to follow!

On not returning a JSON object - understood and agreed, a class of use
cases evaporate with the path ability.  Worst case a serialize element and
construct from buffer wrapping achieves this on the LabVIEW side; likely
inconsequential for all but some performance corner cases (big objects
and/or need for speed).

Will put the new stuff to good use; good timing this side to upgrade FTW,
will check out the updates all around!!

**Comment by JackDunaway** [comment]
I've not committed/pushed a new `ftw32.dll` build yet (hoping to get there today), so I don't recommend trying to integrate these latest pushes, but here's a link to some of the changed code that provides path support: https://github.com/featherweight/featherweight/blob/master/kernel/jansson/ftw_json.c#L50-L235

I'm working on comprehensive type coverage for this new JSON XNode, and have already pushed some new tests dealing with this new [path](https://github.com/featherweight/featherweight/blob/master/tests/core/FTW-Test-JSON-Path.vi) ability, full coverage for [integer overflow behavior](https://github.com/featherweight/featherweight/blob/master/tests/core/FTW-Test-JSON-IntegerOverflow.vi), and a [performance comparison](https://github.com/featherweight/featherweight/blob/master/tests/core/FTW-PerfTest-JSON-Fetch.vi) for JSON deserialization methods.

**Comment by DataFlowLabs** [comment]
Jack, I would like to try some of these new commits out. When do you plan on pushing a new ftw32.dll?

**Comment by jassems** [comment]
Second vote for release, the new path capability will be super helpful for both getter and setter operations!

**Comment by JackDunaway** [comment]
> the new path capability will be super helpful for ... getter ...

Have you checked out `FTW-JSON-Fetch.xnode` from latest (8f89fa21defd7dc46834fd244841c960aa0e2c22)? It's feature-rich; maybe even feature-complete. Drop a new issue with any thoughts. Especially, see the two tests with JSON and Path in the name.

As for setters ... 100% in favor of needing this. It should be relatively straightforward to equip the existing `Set` operations for scalars, and some time would be needed for the generic XNode.

**Comment by jassems** [comment]
Fetch implements this; closing.
