### ISSUE TITLE
Socket Stress Tests Sometimes Fail

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#112]
Communication may not always succeed, but more information on why the test did not pass would be helpful (for example, to explore ways of making the transport more efficient / available on a given machine if necessary).  I also observed only a single test is run for stress tests... it may be insightful to run those tests multiple times (similar to other tests) to see how often each fails.  This may also be insightful as to the cause on a given machine.

<img width="1061" alt="screen shot 2017-06-19 at 5 57 56 pm" src="https://user-images.githubusercontent.com/7451453/27309324-ea91f8b6-5518-11e7-9fdd-7cf3b2dcf936.png">

**Comment by JackDunaway** [comment]
I'm going to close this issue for now, but give a response as to why.

Also, please refer to the commit message at: https://github.com/featherweight/featherweight/commit/7ca12b593d15ff7fa5f8ab1916ab8f4bd007a3d7 ... and note that this feature has begun, but is not fully implemented.

The reason this test fails periodically is because the test is designed to stress the socket connection juuuuust to its breaking point -- which, kinda by definition, means we'll sometimes trip over that breaking point.

The test itself is more designed to ensure no unexpected low-level resource contentions in a massively-concurrent and massively-multi-threaded usage of the socket. It's *not* so much designed to test whether, at the application layer, the application layer concerns are succeeding (i.e., the receipt of 100% of messages).

In reality, this sort of stress test is a good example of what a bad program looks like -- said another way, if your application is using so much of its physical resources that it's failing periodically, the application+hardware system is designed incorrectly.

Yet, intentionally concocting such a nasty test is a great way to flush out 1) access violations, 2) mutex issues, 3) race conditions, and so forth.

So, maybe there should be some sort of pass criterion the test runner acknowledges along the lines of "didn't segfault or deadlock"? In the sense of, the "FAIL" you're receiving here is a "PASS" in disguise ... in the sense of the application (test) neither froze nor crashed.

Hope this helps!

**Comment by jassems** [comment]
Totally helps and makes sense.  Your last paragraph was what came to mind after paragraph 3 - love it, and totally awesome man, thanks for being so thorough with everything!!
