### ISSUE TITLE
JSON Fetch XNode Serializes Numeric Array Elements with String Array Type Specified

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#115]
One might expect that specifying a string array as the type for JSON Fetch would return the default value if an array of that type isn't found.  However, if an numeric array with the same name exists, JSON Fetch will return an array of serialized elements (i.e. corresponding string elements).

<img width="967" alt="screen shot 2017-06-21 at 4 07 48 pm" src="https://user-images.githubusercontent.com/7451453/27407130-d129ba78-569c-11e7-99d2-a3e01c85fa93.png">

Is this a feature or a bug?

**Comment by JackDunaway** [comment]
> Is this a feature or a bug?

You decide :-) But the /behavior/ is indeed intentional.

FYI, if you wanted to do type inspection on the array type, you could query `b[0]` path for its type (and then, assume the array is of homogenous type, or to be thorough albeit a bit inefficient, iterate thru all remaining elements until finding `<invalid>`). Then, case on type to your preferred parsing method.

**Comment by JackDunaway** [comment]
Feel free to re-open with further issues; else, closing this one for now.

**Comment by jassems** [comment]
Cool, I like this... more of a check here in filing the issue... as you noted we can perform the type checking where necessary, else it'll serialize in the simplest case.  Thanks for the quick note here!
