### ISSUE TITLE
JSON Fetch XNode Only Supports 1D Arrays

### ISSUE THREAD

**Issue by jassems** [featherweight/featherweight#117]
We gotta support multidimensional arrays!

<img width="1182" alt="jsonfetchsupports1darraysonly" src="https://user-images.githubusercontent.com/7451453/27462251-0666c0f8-5785-11e7-8173-cd29f27bec16.png">

**Comment by JackDunaway** [comment]
Probably not the answer you want to hear, but this will intentionally not
be supported in FTW. What is allowed in a JSON array -- ragged dimensions
of heterogenous type -- is too permissive for LV restrictions of
rectangular homogeneous array. Not placing a value judgment either way;
just saying the two array protocols are too far apart to reconcile at the
library layer; must stick to the application layer to reconcile >1D arrays.
(It's sticky enough even supporting 1D arrays)

FWIW, feel free to play around with path syntaxes like 'array[n][m]' in
nested FOR loops -- that's fully-supported to pick scalar elements from an
N-dim array. I've not tried explicitly, but a similar strategy may even be
able to select an array type in a single FOR loop.

Kind regards,

- JRD
Sent via mobile

On Jun 22, 2017, at 18:57, jassems <notifications@github.com> wrote:

We gotta support multi-dimensional arrays!

[image: jsonfetchsupports1darraysonly]
<https://user-images.githubusercontent.com/7451453/27460920-9bebe918-577c-11e7-8361-cb3f0f31f44b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/featherweight/featherweight/issues/117>, or mute the
thread

**Comment by jassems** [comment]
Bah, I just spent some time trying to get this to work.  Seems pretty straightforward to support non-composite subarray depth (even of varying lengths, such as [ [1,2], [1,2,3] ] where truncation of longer arrays could apply.  Is there something in `ftw_json_array_element` that prevents getting back a flattened element of type array if its parent is an array?  Admittedly did not go looking yet...

**Comment by JackDunaway** [comment]
> truncation

Already; one sticky topic.

The stated problem mapping N-dim array is not unsolvable; yet it would require FTW to be opinionated on at least 3 orthogonal definitions of "multidimensional vector". That, or configurable to the point of API confusion. This problem domain requires imperative programming at application layer. Since, mapping of disparate JSON<->LV array protocols, it is required to state the app-layer concessions and requirements.

**Comment by JackDunaway** [comment]
Totally open to hearing otherwise! Yet, just doesn't seem this is irreconcible technically; it's the data contract/mapping that's irreconcilable, without imposing app-layer restrictions.

**Comment by jassems** [comment]
I totally understand wanting to escape injecting a bunch of "choices" for how to handle non-homogeneous cases.  Wondering if simply supporting homogeneous cases makes sense though, in the following way.  I may be lacking some perspective on all of the orthogonal considerations here, however truncating at the "innermost array level" to the "smallest size" might be reasonable?  Essentially enforcing this in the recursion IFF your parent was also an array is the idea, however admittedly that hasn't been carried all the way through.  Seems like worst case you'd get error 74 for a "corrupt data type", but for LabVIEW law-abiding multidimensional arrays things would shake out well.

That said, in order to justify even continuing down this path experimentally, is there anything on the C side that would prevent trying this, or would it simply be an update to _FTW-JSON-Core-GetFlattenedValue.vi_?

Thanks!

**Comment by jassems** [comment]
PS - there seemed to be a hint of dimension-consideration in _FTW-JSON-Core-GetFlattenedValue.vi_, else perhaps the array case could be simplified a bit?

**Comment by JackDunaway** [comment]
Err 74 is not cool in any case; bug for sure. Fairly confident that >1D array is at least GetFlattenendValue needing rework, and maaaaybe kernel. Closing this one for now, since I definitely don't disagree with you adding support for such a use-case in a priavte repo or as an optional FTW extension, yet fairly certain it should not be included in FTW Core. LV andJSON are just too far apart spiritually w.r.t. arrays

**Comment by jassems** [comment]
Ok, so could _FTW-JSON-Core-GetFlattenedValue.vi_ simply change as shown below then (and solve [114](https://github.com/featherweight/featherweight/issues/114) along the way)?  Seems to be taking array dimension into consideration otherwise (prepending the full header).

**Old**
<img width="1414" alt="screen shot 2017-06-23 at 12 10 43 am" src="https://user-images.githubusercontent.com/7451453/27467582-3cae1232-57a9-11e7-88aa-a751a0580983.png">


**New**
<img width="1416" alt="screen shot 2017-06-23 at 12 12 43 am" src="https://user-images.githubusercontent.com/7451453/27467585-3fa80d12-57a9-11e7-8173-210c2fde1e28.png">

**Comment by jassems** [comment]
Implemented this; I think this is a worthwhile enhancement.  Will issue a pull request for your perusal which includes:
- fix for [Empty JSON Arrays](https://github.com/featherweight/featherweight/issues/114)
- fix for [Not Handling an Error Cluster in the XNode](https://github.com/featherweight/featherweight/issues/118)
- multidimensional array support (this issue)

**Comment by jassems** [comment]
@JackDunaway - can we reopen this issue until after you've inspected the update, and we have maybe one more go-round of love on this issue?  

**Goal**: add multidimensional array capability without causing new problems - see the **Arguments for...** below as well.

**Thought**: let's set aside the truncation issue for a second (we'll come back to it).  If my understanding is correct, all that's happening with arrays - regardless of the number of dimensions - is packing "headers" (dimensions sizes) out in front of the list of elements (even if there are zero elements ;-).

**Memory / mental model for N-dimensional array with a total of M elements spanning all dimensions:** 

`<dim[N]><dim[N-1]>...<dim[1]><el[0]><el[1]>...<el[M]>` 

When viewed this way, there's little difference between the 1D and N-dimensional cases; just more headers in front of data.  I say little because there are differences.  In particular, there seem to be two key issues to deal with, one of which was already handled in Fetch and the other being the choice between array truncation vs "default-value-fill".

- **Issue 1 (same for any number of dimensions): Incongruent Elements** - already handled in Fetch.  For example, `[{"a":1, "b":[1,2,3]}, {"a":2}]` will resolve in LabVIEW to `[{"a":1, "b":[1,2,3]}, {"a":2, "b":[]}]` owing to how the underlying element-level flattening preserves the full input LabVIEW data type (assuming you specified the "superset" data type which includes the "b" array).  Let's call this **friendly** assumption **Type Superset Defaulting Feature** and note that it works happily for 1D arrays owing to the recursion (and therefore should happily work for N-dimensional arrays).  

_I say **friendly** here because it works well for 99.9% of use cases, and you can write application code for the 0.1% otherwise without harm._


- **Issue 2 (unique to N > 1 dimensions): Array Truncation vs "Default-Value-Fill"** - either way would seem to work in theory, but I tend to favor truncation for simplicity and sanity.  To be clear, this is NOT about truncating the fundamental data type underlying the array; the existing **Type Superset Defaulting Feature** seems to handle this class of cases pretty gracefully at the element level.  Rather, this is about truncating only the **number of elements** in a given dimension to match that of the smallest within that dimension.  For example, '{"a":[[1,2,3], [4,5]]}' would get truncated to '{"a":[[1,2], [4,5]]}'.  In words, it says that each row has to be the same length (because LabVIEW requires this), and we're not going to "zero-fill" here, but instead truncate all rows to the smallest row length.  The application can happily "zero-fill" a priori in such a case of course, if that's the intended behavior.  Importantly, the truncation analogy persists for higher dimensions and is seemingly gracefully implemented at the "flattened" level (I'm referring to an implementation detail here, where a flattened array - to string - is easily truncated, naturally stripping off the "extra" elements).  Let's call this **friendly** assumption **Multidimensional Array Consistency Truncation**.  

_I, again, say **friendly** here because (I think...) it works well for 99.9% of use cases, and you can write application code for the 0.1% otherwise without harm._


**Arguments for Multidimensional Array Support**
- saves a bunch of app-level code for handling multidimensional arrays
- solves 99.9% of use cases gracefully (existing app-level approach still there anyway)
- doesn't add meaningful complexity to the flattening algorithm (owing to the array mental model above, it's really just dimension header bookkeeping)
- support for multidimensional arrays!! :)


Looking forward to any thoughts!
