### ISSUE TITLE
FTW-Inbox-Destroy.vi hangs

### ISSUE THREAD

**Issue by andrejpanjan** [featherweight/featherweight#68]
Running the FTW-Test-Socket-Stress-InboxConnector.vi with "10 parallel clients, 100 messages, 10kB payload" and clicking the STOP button will make the FTW-Inbox-Destroy.vi to hang (at Call Library function ftw_socket_destroy).

The same issue was also observed in my application with only two actors running.

**Comment by JackDunaway** [comment]
I'm not able to reproduce this readily, but it feels like a race condition based on hardware configuration (i.e., I'm running in a virtual machine, which may be slow enough to make reproduction harder)

Would you run `FTW-Test.vi` and copy the top lines from the output? For instance, here's mine:

```
Timestamp:       2016-05-24T17:09:57.247Z
FTW Version:     0.7.0
Environment:     LabVIEW 2015 (15.0.1f3)
App Instance:    Development System (LabVIEW.exe)
OS:              Windows 8.1 Enterprise  (v6.3, build 9600)
Language:        en
CPU:             Intel x86 (4 cores, 4 processors)
```

**Comment by andrejpanjan** [comment]
Sure ... see below

```
Timestamp:       2016-05-24T18:04:33.206Z
FTW Version:     0.7.0
Environment:     LabVIEW 2015 (15.0.1f3)
App Instance:    Development System (LabVIEW.exe)
OS:              Windows 10 Pro  (v10.0, build 10586)
Language:        en
CPU:             Intel x86 (2 cores, 4 processors)
```

**Comment by JackDunaway** [comment]
I'll try throttling my VM to have 2 cores ...

**Comment by JackDunaway** [comment]
I have finally reproduced this ... stay tuned ...

**Comment by JackDunaway** [comment]
It is hanging right here:

https://github.com/featherweight/featherweight/blob/5b94915c08fec2bea304ea4b0b8b5657d8e4e9ff/kernel/framework/ftw_framework.c#L100

and since that thread is hung, the ftw_socket_destroy hangs here:

https://github.com/featherweight/featherweight/blob/5b94915c08fec2bea304ea4b0b8b5657d8e4e9ff/kernel/nanomsg/ftw_nanomsg.c#L571

The reason it's hanging is because the LabVIEW side is destroying its references prior to acknowledging and waking up the underlying inbox thread that it's "ready for the next message":

https://github.com/featherweight/featherweight/blob/5b94915c08fec2bea304ea4b0b8b5657d8e4e9ff/kernel/framework/ftw_framework.c#L204

I'm investigating the best fix ... stay tuned ...
