### ISSUE TITLE
SQLite API doesn't return correct values for some fields

### ISSUE THREAD

**Issue by andrejpanjan** [featherweight/featherweight#82]
Some fields are not correct while other fields from the same table are correct.

`C-SQLite-Test.vi` from the attached example demonstrates such behavior.

[DB bug.zip](https://github.com/featherweight/featherweight/files/318284/DB.bug.zip)

**Comment by JackDunaway** [comment]
I've tried to reproduce by copy and pasting the SQL from here:

![screen shot 2016-06-16 at 8 41 56 am](https://cloud.githubusercontent.com/assets/1944203/16118782/4349dafc-339e-11e6-98c9-fc1e07476592.png)

into a third party [DB Browser for SQLite](http://sqlitebrowser.org/), and it returns the following error:

`no such column: measurement_CMJ.measurement_CMJ@P3_F_at_Peak_Eccentric_–_P3`

Investigating further, `PRAGMA table_info(measurement_CMJ);` returns what looks like a character with an encoding that's not rendering properly on that particular column:

![screen shot 2016-06-16 at 8 40 19 am](https://cloud.githubusercontent.com/assets/1944203/16118812/5cc2603a-339e-11e6-8aa3-2bd4509c72ce.png)

Now, we could be getting off track by debugging DB Browser, but on the other hand it could be related to the failure mode we're seeing within FTW-SQLite, since it feels like we're dealing with an encoding issue here (related: #81)

Looking at the "offending" column in LV, we get the following underlying bytes for that column:

![screen shot 2016-06-16 at 8 55 29 am](https://cloud.githubusercontent.com/assets/1944203/16119357/be3a37f0-33a0-11e6-905b-6128a6f2bf91.png)

Looking toward the end, you'll see `5F 96 5F`, which is an underscore, "single-byte-mystery-code-point", underscore.

I reckon that the `96` is doing something like this: http://stackoverflow.com/questions/3005515/does-the-character-96-hex-have-any-special-meaning-in-internet-protocols-formats

A similar bug bit me in an application a few years back -- turns out, there are MANY unicode points that represent dashes and hyphens -- where, the differences in their rendering is mostly undetectable unless compared side-by-side -- and insidiously, some are automatically converted from one to the other when going across application boundaries.

@andrejpanjan Can you investigate any further along this path? Or, provide a more minimal test case that eliminates the possibility of encoding being the problem (or, that encoding is exactly the problem)? Thanks!

**Comment by JackDunaway** [comment]
By the way, I'll try to see if #83 helps in any way. The query you're executing here is pretty in-depth, so there's some chance this is a SQLite issue rather than FTW (very unlikely, but #83 sure won't hurt!)

**Comment by JackDunaway** [comment]
Much better! I'll look into this today and report back. Been tied up with #68, but that's hopefully got a fix coming today.
